### ISSUE TITLE
Reverb.js on html with cdn.

### ISSUE THREAD

**Issue by jomin398** [logue/Reverb.js#2]
how to use code?

i tried to use with `umd.js`;
it't throws error.

- Reverb.umd.js:22 Uncaught TypeError: Cannot read properties of undefined (reading 'SYSTEM')
   at Reverb.umd.js:22:29
   at Reverb.umd.js:15:94
   at Reverb.umd.js:12:1

i tried again with cdn.
```js
import { default as Reverb } from "reverb"; 
var context = new AudioContext();
    let el = document.querySelector("audio");
var source = context.createMediaElementSource(el);
    var reverb = new Reverb(context, {
      noise: 'pink',
      time: 6,
      decay: 25,
      delay: 4,
      reverse: false
    });
    await reverb.ready;
    reverb.connect(source);
    source.connect(context.destination);
```

but effect is dosen't work. (No audio)
how to fix it?

**Comment by logue** [comment]
It seems that the package it depends on is not loaded.
I think it will work if you read it with esm.

https://www.jsdelivr.com/package/npm/@thi.ng/colored-noise
